In [1]:
import os
import requests
from requests.auth import HTTPBasicAuth
import numpy as np
import pandas as pd
from netCDF4 import Dataset
from datetime import datetime,date
import time
import xarray as xr

In [2]:
os.chdir('D://BIT_study_related//Thesis//Data_Monthly//OCO-2//netcdf')
os.getcwd()

'D:\\BIT_study_related\\Thesis\\Data_Monthly\\OCO-2\\netcdf'

In [ ]:
username = 'shreyas_rc'
password = 'Chetna@16'

try:
    def download():
        file = open('link.txt', 'r')
        for line in file:    
            URL = line
            i = 0
            name = ''
            for i in range(0,6):
                name = name + line[140+i]
                i += 1
            result = requests.get(URL, auth = HTTPBasicAuth(username, password), allow_redirects = True)
            result.raise_for_status()
            f = open('OCO2_'+name+'.nc','wb')
            f.write(result.content)
            f.close()
            print('contents of URL written to '+name+'.nc')
        file.close()
    download()
except requests.exceptions.TooManyRedirects:
    print("Calling the function again")
    download()

In [ ]:
directory = 'D:\\BIT_study_related\\Thesis\\Data_Monthly\\OCO-2\\netcdf'
for root, _, files in os.walk(directory):
    for f in files:
        fullpath = os.path.join(root, f)
        try:
            # set the threshold file size to delete in bytes
            if os.path.getsize(fullpath) < 1200:   
                print(fullpath)
                os.remove(fullpath)
        except WindowsError:
            print("Error" + fullpath)

In [ ]:
data = Dataset('OCO2_151218.nc')
data["pressure_levels"]

In [ ]:
directory = 'D:\\BIT_study_related\\Thesis\\Data_Monthly\\OCO-2\\netcdf'

def conv_date(d):
    return datetime.strptime(str(d), '%Y%m%d%H%M%S%f')
for files in os.listdir(directory):
    y = ''
    m = ''
    d = ''
    data = Dataset(files)
    df_xco2= pd.DataFrame(columns=["DateTime", "Latitude", "Longitude", "xco2", "xco2_quality_flag","pressure_levels"])
    df_xco2["xco2"]= data["xco2"][:]
    df_xco2["pressure_levels"]= data["pressure_levels"][:]
    df_xco2["DateTime"]= data["sounding_id"][:]
    df_xco2["Latitude"]= data["latitude"][:]
    df_xco2["Longitude"]= data["longitude"][:]
    df_xco2["xco2_quality_flag"]= data["xco2_quality_flag"][:]
    df_xco2["DateTime"]= df_xco2["DateTime"].apply(conv_date)
    df_xco2["DateTime"]= pd.to_datetime(df_xco2["DateTime"])
    df_xco2["Year"]= df_xco2["DateTime"].dt.year
    df_xco2["Month"]= df_xco2["DateTime"].dt.month
    df_xco2["Day"]= df_xco2["DateTime"].dt.day
    y = str(df_xco2.Year[0])
    if y == '2023':
        m = str(df_xco2.Month[0])
        d = str(df_xco2.Day[0])
        ymd = y+str('_')+m+str('_')+d
        df_xco2.to_csv('D://BIT_study_related//Thesis//Data_Monthly//OCO-2//2023//OCO-2_'+ymd+'.csv')

In [21]:
os.chdir('D:\\BIT_study_related\\Thesis\\Data_Monthly\\OCO-2\\2023')
os.getcwd()

'D:\\BIT_study_related\\Thesis\\Data_Monthly\\OCO-2\\2023'

In [22]:
directory1 = 'D:\\BIT_study_related\\Thesis\\Data_Monthly\\OCO-2\\2023'
df_concat = pd.concat([pd.read_csv(f) for f in os.listdir(directory1) ], ignore_index=True)
df_concat.drop(df_concat.columns[[0]], axis=1, inplace=True)
df_concat.to_csv('D:\\BIT_study_related\\Thesis\\Data_Monthly\\OCO-2\\OCO-2_23.csv')
df_concat

,DateTime,Latitude,Longitude,xco2,xco2_quality_flag,pressure_levels,Year,Month,Day
0,2023-01-01 07:46:01.730,4.543575,84.851006,418.63422,1,0.101624,2023,1,1
1,2023-01-01 07:46:02.030,4.562138,84.846690,419.68076,1,0.101133,2023,1,1
2,2023-01-01 07:46:02.040,4.551544,84.851240,418.46470,1,0.101620,2023,1,1
3,2023-01-01 07:46:02.050,4.540987,84.855675,418.61240,1,0.101526,2023,1,1
4,2023-01-01 07:46:02.330,4.580705,84.842390,417.90080,1,0.101525,2023,1,1
...,...,...,...,...,...,...,...,...,...
121822,2023-02-09 07:57:36.080,21.853560,79.377780,418.35464,0,0.094760,2023,2,9
121823,2023-02-09 07:57:36.360,21.892326,79.358510,419.34473,0,0.094634,2023,2,9
121824,2023-02-09 07:57:36.370,21.882093,79.365720,419.59448,0,0.094570,2023,2,9
121825,2023-02-09 07:57:36.380,21.871810,79.372870,419.50037,0,0.094591,2023,2,9
121826,2023-02-09 07:57:36.780,21.890009,79.367874,418.46323,0,0.094943,2023,2,9